#!/usr/bin/env ruby

require_relative 'legendas_tv/release'
require_relative 'legendas_tv/service' rescue exit
require 'io/console'
require 'colorize'
require 'optparse'
require 'pathname'

EXTENSIONS = %w(.avi .flv .m4v .mkv .mov .mp4 .mpeg .mpg .ogv .rmvb .ts .webm .wmv).freeze

def login
  print 'Enter your username: '
  username = STDIN.gets.chomp

  print 'Enter your password: '
  password = STDIN.noecho(&:gets).chomp

  puts "\n\n"

  with_progress('Logging in') { @service.login(username, password) }

  puts "Logged in as #{username}"
rescue => e
  puts e.message
  exit
end

def with_progress(message)
  t = Thread.new do
    loop do
      4.times do |i|
        STDOUT.write "#{message}#{'.' * i}#{' ' * (4 - i)}\r"
        sleep 0.333
      end
    end
  end

  yield

  t.exit
end

def should_download?(path)
  unless EXTENSIONS.include?(path.extname)
    puts "File #{path.basename} ignored. " \
         "\"#{path.extname}\" doesn't seem to be a video extension." if @verbose
    return false
  end

  if File.exist?(path.to_s.gsub(path.extname, '.srt'))
    puts "Subtitle for '#{path.basename}' already downloaded".blue if @verbose
    return false
  end

  false
end

def find_subtitle(path)
  puts "Searching subtitles for \"#{path.to_s.italic.bold.light_magenta}\"" if @verbose

  unless should_download?(path)
    puts if @verbose
    return
  end

  release = LegendasTV::Release.new(path.basename)

  @service.working_dir = path.dirname

  subtitles = @service.find_and_download(release)

  puts if @verbose
rescue => e
  puts "Error: #{e.message} (file \"#{path.to_s}\")".red
end

@verbose = false
@service = LegendasTV::Service.new

ARGV.push('-h') if ARGV.empty?

OptionParser.new do |opts|
  opts.banner = 'Usage: legendastv [options] <file_path>'

  opts.on('-h', '--help', 'Display this help') { puts opts; exit }
  opts.on('-l', '--logout', 'Logs the current user out') { @service.logout }
  opts.on('-v', '--verbose', 'Extensive logs') { @verbose = true }
end.parse!

exit if ARGV.empty?

login unless @service.logged_in?

ARGV.each do |arg|
  path = Pathname.new(arg).realdirpath

  if path.file?
    find_subtitle(path)
  elsif path.directory?
    Dir.glob(arg + '/**/*').each do |filepath|
      path = Pathname.new(filepath)

      find_subtitle(path)
    end
  else
    puts "Invalid path '#{path}'".yellow
  end

end
